defaultLanguageName: node

enableColors: true

networkConcurrency: 8

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

npmScopes:
  expertsystems:
    npmRegistryServer: https://registry.exsysdev.com/repository/npm-expertsystems/
    npmAlwaysAuth: true
    npmAuthIdent: Z2VuZXJpYy1kZXY6bDMzdHN1cGFoNHgwcg==
npmPublishAccess: restricted
